
ICONDIR = ~/.local/share/icons/

install:
	test -d $(ICONDIR) || mkdir $(ICONDIR)
	cp lark-gui.png $(ICONDIR)
	cp lark-launcher.png $(ICONDIR)
	cp larkgui.desktop ~/Desktop/
	cp larklauncher.desktop ~/Desktop/